### ISSUE TITLE
Elevate permissions to admin

### ISSUE THREAD

**Issue by mike3run** [jeualvarez/RT#1]
Hey there @jeualvarez i'd like to set up a demo using Netlify so its automatic on every push, could you add me as admin for the repo so i can set that CI.

Otherwise, you could set that up the command needed to build the site is:

`yarn build:normal`

while serving the

`dist`

Directory

thanks!!

**Comment by jeualvarez** [comment]
Hey @mike3run I noticed that I did not created an Organization but a single Repo. So I can only add collaborators and I can not add them as admins. Correct me if I am wrong.

If that's the case I can send the credentials to Maureen so you can do it with my user.

Best

**Comment by mike3run** [comment]
@jeualvarez you are correct 🤔 then yeah we can do that with Maureen

**Comment by mike3run** [comment]
All good now
